name: 'AmTrav x Airtable Action'
description: 'Parse AmTrav CSV reports into Airtable'
inputs:
  airtable-api-key:
    description: 'The Airtable API key to use for Airtable interactions'
    required: true
  airtable-base-id:
    description: 'The ID of the Airtable Base used in the target program'
    required: true
  airtable-import-record-id:
    description: 'The ID of the Airtable Record whose CSVs should be parsed and integrated'
    required: true
  amtrav-card-id:
    description: 'The ID of the AmTrav Credit Card whose transactions should be integrated'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
