name: Amex Workflow
on:
  repository_dispatch:
    types: [amex_csv]
  workflow_dispatch:
    inputs:
      airtable-import-record-id:
        description: 'Airtable Import Record ID'
        required: true
        type: string
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: RSTechTeam/airtable-integrations/.github/actions/amex@main
        with:
          airtable-api-key: ${{ secrets.AIRTABLE_API_KEY }}
          airtable-base-id: ${{ secrets.EXPENSE_SOURCES_BASE_ID }}
          airtable-import-record-id:
            ${{ github.event.client_payload.airtable-import-record-id || inputs.airtable-import-record-id }}
